"""create stage 4 identity and core business schema

Revision ID: 0002_core_api
Revises: 0001_empty_baseline
Create Date: 2026-07-17 09:19:50.205086
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_core_api"
down_revision: str | Sequence[str] | None = "0001_empty_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'disabled')", name="ck_users_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("activity_type", sa.String(length=60), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("intensity", sa.String(length=20), nullable=False),
        sa.Column("energy_kcal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_ref", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "intensity IN ('low', 'moderate', 'high')", name="ck_activity_intensity"
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'agent', 'image', 'import')", name="ck_activity_source"
        ),
        sa.CheckConstraint(
            "duration_minutes > 0 AND duration_minutes <= 1440", name="ck_activity_duration"
        ),
        sa.CheckConstraint("energy_kcal >= 0 AND energy_kcal <= 20000", name="ck_activity_energy"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activity_records_user_created",
        "activity_records",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_activity_records_user_date",
        "activity_records",
        ["user_id", "record_date"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_user_created", "audit_events", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_auth_sessions_user_active", "auth_sessions", ["user_id", "revoked_at"], unique=False
    )
    op.create_table(
        "food_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("meal_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("portion_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("portion_unit", sa.String(length=30), nullable=True),
        sa.Column("energy_kcal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("protein_g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("carbs_g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fat_g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_ref", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "meal_type IN ('breakfast', 'lunch', 'dinner', 'snack', 'other')", name="ck_food_meal"
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'agent', 'image', 'import')", name="ck_food_source"
        ),
        sa.CheckConstraint("energy_kcal >= 0 AND energy_kcal <= 20000", name="ck_food_energy"),
        sa.CheckConstraint("portion_amount IS NULL OR portion_amount > 0", name="ck_food_portion"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_food_records_user_created", "food_records", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_food_records_user_date", "food_records", ["user_id", "record_date"], unique=False
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("target_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("daily_energy_target_kcal", sa.Integer(), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('lose_fat', 'gain_muscle', 'maintain')", name="ck_goals_kind"),
        sa.CheckConstraint(
            "daily_energy_target_kcal IS NULL OR "
            "(daily_energy_target_kcal >= 800 AND daily_energy_target_kcal <= 10000)",
            name="ck_goals_daily_energy",
        ),
        sa.CheckConstraint(
            "target_weight_kg IS NULL OR (target_weight_kg >= 25 AND target_weight_kg <= 400)",
            name="ck_goals_target_weight",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_goals_user_active", "goals", ["user_id", "is_active"], unique=False)
    op.create_index(
        "uq_goals_one_active",
        "goals",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=160), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "method", "path", "key", name="uq_idempotency_scope"),
    )
    op.create_index("ix_idempotency_expires", "idempotency_keys", ["expires_at"], unique=False)
    op.create_table(
        "identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("normalized_value", sa.String(length=254), nullable=False),
        sa.Column("display_value", sa.String(length=254), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('email', 'username', 'phone')", name="ck_identities_kind"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "normalized_value", name="uq_identities_kind_value"),
    )
    op.create_index("ix_identities_user_kind", "identities", ["user_id", "kind"], unique=False)
    op.create_table(
        "password_credentials",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("sex", sa.String(length=20), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("preferred_unit", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("preferred_unit IN ('metric', 'imperial')", name="ck_profiles_unit"),
        sa.CheckConstraint(
            "sex IS NULL OR sex IN ('female', 'male', 'other', 'undisclosed')",
            name="ck_profiles_sex",
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR (height_cm >= 80 AND height_cm <= 250)", name="ck_profiles_height"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "weight_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source IN ('manual', 'agent', 'image', 'import')", name="ck_weight_source"
        ),
        sa.CheckConstraint("weight_kg >= 25 AND weight_kg <= 400", name="ck_weight_value"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_weight_records_user_date", "weight_records", ["user_id", "record_date"], unique=False
    )
    op.create_index(
        "ix_weight_records_user_measured",
        "weight_records",
        ["user_id", "measured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_weight_records_user_measured", table_name="weight_records")
    op.drop_index("ix_weight_records_user_date", table_name="weight_records")
    op.drop_table("weight_records")
    op.drop_table("profiles")
    op.drop_table("password_credentials")
    op.drop_index("ix_identities_user_kind", table_name="identities")
    op.drop_table("identities")
    op.drop_index("ix_idempotency_expires", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("uq_goals_one_active", table_name="goals", postgresql_where=sa.text("is_active"))
    op.drop_index("ix_goals_user_active", table_name="goals")
    op.drop_table("goals")
    op.drop_index("ix_food_records_user_date", table_name="food_records")
    op.drop_index("ix_food_records_user_created", table_name="food_records")
    op.drop_table("food_records")
    op.drop_index("ix_auth_sessions_user_active", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_audit_user_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_activity_records_user_date", table_name="activity_records")
    op.drop_index("ix_activity_records_user_created", table_name="activity_records")
    op.drop_table("activity_records")
    op.drop_table("users")
    # ### end Alembic commands ###
